#: Police
font_family      Hack Nerd Font
font_size        10
font_hint        light
adjust_line_height 2
bold_font        auto
italic_font      auto
bold_italic_font auto

#: Curseur
cursor_text_color    background
cursor_shape         beam
cursor_blink_interval 0

#: Fenetre
hide_window_decorations yes
remember_window_size  yes
initial_window_width  100c
initial_window_height 30c
window_padding_width  0
window_margin_width   0
single_window_margin_width 0
active_border_color   #b8bb26
inactive_border_color #282828
inactive_text_alpha   0.8

#: Onglets
tab_bar_style fade
tab_bar_min_tabs 2
tab_title_template {title}
active_tab_foreground   #ebdbb2
active_tab_background   #282828
inactive_tab_foreground #928374
inactive_tab_background #282828

#: Sonnerie
enable_audio_bell  no
visual_bell_duration 0
window_alert_on_bell no
bell_on_tab        no

#: Scrollback
scrollback_lines 10000

#: Couleurs
background           #282828
foreground           #ebdbb2
background_opacity   0.95
dynamic_background_opacity yes
background_noise_level 0.2
include ./theme.conf

#: Curseur orange
cursor #e66100
#: Vert plus clair
color2 #b8bb26

#: sélectionner = copier
copy_on_select clipboard

#: clic + Ctrl+Shift pour ouvrir un URL
open_url_modifiers kitty_mod

#: intégration shell kitty (prompts, titres, sélection de outputs)
shell_integration enabled

#: Raccourcis
kitty_mod ctrl+shift

#: Navigation entre prompts (shell_integration)
map kitty_mod+alt+p goto_previous_prompt
map kitty_mod+alt+n goto_next_prompt
